import type { LearningLesson } from "../types/models.js";


export const learningLessons: LearningLesson[] = [
    {
        "id": "introduction-001",
        "title": "Welcome",
        "description": "Hi there. Welcome to TypeHard. In TypeHard we learn how to type fast and accurately. You're currently in the 'Learn' menu, You can go to the 'Lessons' from the menu bar, select 'Touch Typing' to choose a lesson or stay here with me to start learning. Press the right arrow key to start your very first lesson...",
        "text": "",
        "category": "introduction",
        "order": 1,
        "introducedKeys": [],
    },
    {
        "id": "home-row-001",
        "title": "F & J Keys",
        "description": "We all know that you cannot learn a skill without learning the fundamentals. Even though these first lessons seem a bit boring, the consistency will make you a good typist. Simply put your left index finger on the F key and your right index finger on the J key. Start typing the letters below, and remember accuracy is more important than speed!",
        "text": "ffff jjjj ffjj jjff fjfj jfjf fjff jfjj",
        "category": "home-row",
        "order": 2,
        "introducedKeys": ["f", "j"],
    },
    {
        "id": "home-row-002",
        "title": "D & K keys",
        "description": "Okay, so we talked about the index fingers, now it's time for the next finger. As you keep your index fingers on the F and J keys, put your left middle finger on the D key and your right middle finger on the K key. Start doing the exercise.",
        "text": "dddd kkkk ddkk kkdd dkdk kdkd dkdd kdkk",
        "category": "home-row",
        "order": 3,
        "introducedKeys": ["d", "k"],
    },
    {
        "id": "home-row-003",
        "title": "D, F, J, & K keys",
        "description": "All good. But I think it's time to slow down a bit. Touch typing is all about muscle memory and the more you train your muscle memory, the better you become. Let's review what we've learned in the past two lessons.",
        "text": "dddd ffff jjjj kkkk ddff jjkk ffdd kkjj dfjk kjfd dfjd kjfk jfkd fjdk",
        "category": "home-row",
        "order": 4,
        "introducedKeys": ["d", "f", "j", "k"],
    },
    {
        "id": "home-row-004",
        "title": "S & L keys",
        "description": "So far, so good. The key point to touch typing is consistency. You should be careful not to go back to typing with one finger. Sometimes this even seems easier for beginners but remember it's all about habits. So keep your fingers as discussed with your ring fingers on the S and L keys.",
        "text": "ssss llll ssll llss slsl lsls slss lsll sssl llls",
        "category": "home-row",
        "order": 5,
        "introducedKeys": ["s", "l"],
    },
    {
        "id": "home-row-005",
        "title": "A & ; keys",
        "description": "This can be a bit boring but I promise we'll get to the hard part too :) As you type, you should also be aware of where you're looking. Even if typing becomes slower, try to look at the screen. It's okay to look at the keyboard but if you constantly look at the keyboard then you won't develop strong muscle memory. Now put your little fingers on the A and ; keys and start typing.",
        "text": "aaaa ;;;; aa;; ;;aa a;a; ;a;a ;a;; a;aa aaa; ;;;a",
        "category": "home-row",
        "order": 6,
        "introducedKeys": ["a", ";"],
    },
    {
        "id": "home-row-006",
        "title": "g & h keys",
        "description": "As you may have figured this out yourself, the index fingers do twice as much work as the other fingers. On the home row, the index fingers actually cover the F, G, H, and J keys. Keep you index fingers on the F and J keys and reach for the G and H keys when necessary, then return your fingers to F and J.",
        "text": "gggg hhhh gghh hhgg ghgh hghg ghgg hghh gggh hhhg",
        "category": "home-row",
        "order": 7,
        "introducedKeys": ["g", "h"],
    },
    {
        "id": "home-row-007",
        "title": "Home row mastery",
        "description": "Alright, alright, alright. Now it's time for the final test of the home row. You've learned the ten keys of the home row. It's okay if you feel like you're not fast enough yet. Keep practicing and don't give up.",
        "text": "sad lag gal lfh jfk dl; gha hhs kd; lfk dka jk; dks ajf skk ldj jfj",
        "category": "home-row",
        "order": 8,
        "introducedKeys": ["a", "s", "d", "f", "g", "h", "j", "k", "l", ";"],
    },
    {
        "id": "introduction-002",
        "title": "Introduction to the Top Row",
        "description": "Now that you know all the keys from the home row, it's time to start learning the top row. The top row is actually straightforward, nothing tricky about it. The key is to keep your fingers on the home row, reach for the top-row keys when necessary, and then return your fingers to the home row. Press the right arrow key if you're ready.",
        "text": "",
        "category": "introduction",
        "order": 9,
        "introducedKeys": [],
    },
    {
        "id": "top-row-001",
        "title": "R & U keys",
        "description": "Try to reach the R and U keys using your index fingers. Ready? Let's start.",
        "text": "rrrr uuuu rruu uurr ruru urur rurr uruu rrru uuur",
        "category": "top-row",
        "order": 10,
        "introducedKeys": ["r", "u"],
    },
    {
        "id": "top-row-002",
        "title": "E & I keys",
        "description": "The same rule applies here. As you keep your middle fingers on the D and K keys, try to reach the E and I keys. Now that we're going through the top row keys, your fingers may start to feel a little tired. But that's alright. And remember, just like with any physical activity, your fingers may need some rest too. So start if you're ready.",
        "text": "eeee iiii eeii iiee eiei ieie eiee ieii",
        "category": "top-row",
        "order": 11,
        "introducedKeys": ["e", "i"],
    },
    {
        "id": "top-row-003",
        "title": "Review keys",
        "description": "There you go! Don't worry, I don't mean to bother you. See? I told you that touch typing is all about muscle memory. To become a better typist, you need to go back to these lessons once in a while. Let's review what we've learned so far.",
        "text": "kid hug ill elf fill jedi fake; jar jake hulk laugh judge; fish jail flash flake freak shrek; sugar lifeguard",
        "category": "top-row",
        "order": 12,
        "introducedKeys": ["a", "s", "d", "f", "g", "h", "j", "k", "l", ";", "e", "r", "u", "i"],
    },
    {
        "id": "top-row-004",
        "title": "W & O keys",
        "description": "Bravo. I knew you could do this. Let's take it to the next level. As discussed, try to reach the W and O keys using your ring fingers.",
        "text": "wwww oooo wowo owow wwoo ooww woww owoo",
        "category": "top-row",
        "order": 13,
        "introducedKeys": ["w", "o"],
    },
    {
        "id": "top-row-005",
        "title": "Review keys",
        "description": "One of the reasons I insist on constant practice is to make sure you learn every key correctly. See, If we move from lesson to lesson or from letter to letter, your finger positions won't become consistent. As I said accuracy matters more than speed, so try to write these words with as few mistakes as possible.",
        "text": "how who folk goes awake; joke where work walk wife flow firework flush; field shower dialog goldfish; selfish forehead sword",
        "category": "top-row",
        "order": 14,
        "introducedKeys": ["a", "s", "d", "f", "g", "h", "j", "k", "l", ";", "e", "r", "u", "i", "w", "o"],
    },
    {
        "id": "top-row-006",
        "title": "Q & P keys",
        "description": "This one could be a little tricky. Since the little fingers are actually little you may need to raise your hand a bit to reach these keys, and that is totally fine. Now keep your fingers on the home row and try to reach the Q and P keys with your little fingers.",
        "text": "qqqq pppp qqpp ppqq qpqp pqpq qpqq pqpp",
        "category": "top-row",
        "order": 15,
        "introducedKeys": ["q", "p"],
    },
    {
        "id": "top-row-007",
        "title": "Review keys",
        "description": "You're almost there, don't quit.",
        "text": "worship square soldier shop graph paul paw war hill help joe desire life rope south power pole pool floor",
        "category": "top-row",
        "order": 16,
        "introducedKeys": ["a", "s", "d", "f", "g", "h", "j", "k", "l", ";", "e", "r", "u", "i", "w", "o", "q", "p"],
    },
    {
        "id": "top-row-008",
        "title": "T & Y keys",
        "description": "And last but not least the T and Y keys. As you've probably figured out by now, the index fingers cover the F, G, H, and J keys from the home row and the R, T, Y, and U keys from the top row. Now are you ready? Let's do this.",
        "text": "tttt yyyy ttyy yytt tyty ytyt tytt ytyy",
        "category": "top-row",
        "order": 17,
        "introducedKeys": ["t", "y"],
    },
    {
        "id": "top-row-009",
        "title": "Top row mastery",
        "description": "I have to say I'm proud of you. A lot of people would quit around here, but you're not a quitter, are you? Show me what you got.",
        "text": "up pie pre pot put pity poet equip quality tower writeup turkey ritual grape kiwi flash ride dollar lead seat stalk drop toward lake earth hospital",
        "category": "top-row",
        "order": 18,
        "introducedKeys": ["a", "s", "d", "f", "g", "h", "j", "k", "l", ";", "e", "r", "u", "i", "w", "o", "q", "p", "t", "y"],
    },
]