import type { LearningLesson } from "../types/models.js";


export const learningLessons: LearningLesson[] = [
    {
        "id": "introduction-001",
        "title": "Welcome",
        "description": "Hi there. Welcome to TypeHard. In TypeHard we learn how to type fast and accurately. You're currently in the 'Learn' menu, You can go to the 'Lessons' from the menu bar, select 'Touch Typing' to choose a lesson or stay here with me to start learning. Press the right arrow key to start your very first lesson...",
        "text": "",
        "category": "introduction",
        "order": 1,
        "introducedKeys": [],
    },
    {
        "id": "home-row-001",
        "title": "F & J Keys",
        "description": "We all know that you cannot learn a skill without learning the fundamentals. Even though these first lessons seem a bit boring, the consistency will make you a good typist. Simply put your left index finger on the F key and your right index finger on the J key. Start typing the letters below, and remember accuracy is more important than speed!",
        "text": "ffff jjjj ffjj jjff fjfj jfjf fjff jfjj",
        "category": "home-row",
        "order": 2,
        "introducedKeys": ["f", "j"],
    },
    {
        "id": "home-row-002",
        "title": "D & K keys",
        "description": "Okay, so we talked about the index fingers, now it's time for the next finger. As you keep your index fingers on the F and J keys, put your left middle finger on the D key and your right middle finger on the K key. Start doing the exercise.",
        "text": "dddd kkkk ddkk kkdd dkdk kdkd dkdd kdkk",
        "category": "home-row",
        "order": 3,
        "introducedKeys": ["d", "k"],
    },
    {
        "id": "home-row-003",
        "title": "D, F, J, & K keys",
        "description": "All good. But I think it's time to slow down a bit. Touch typing is all about muscle memory and the more you train your muscle memory, the better you become. Let's review what we've learned in the past two lessons.",
        "text": "dddd ffff jjjj kkkk ddff jjkk ffdd kkjj dfjk kjfd dfjd kjfk jfkd fjdk",
        "category": "home-row",
        "order": 4,
        "introducedKeys": ["d", "f", "j", "k"],
    },
    {
        "id": "home-row-004",
        "title": "S & L keys",
        "description": "So far, so good. The key point to touch typing is consistency. You should be careful not to go back to typing with one finger. Sometimes this even seems easier for beginners but remember it's all about habits. So keep your fingers as discussed with your ring fingers on the S and L keys.",
        "text": "ssss llll ssll llss slsl lsls slss lsll sssl llls",
        "category": "home-row",
        "order": 5,
        "introducedKeys": ["s", "l"],
    },
    {
        "id": "home-row-005",
        "title": "A & ; keys",
        "description": "This can be a bit boring but I promise we'll get to the hard part too :) As you type, you should also be aware of where you're looking. Even if typing becomes slower, try to look at the screen. It's okay to look at the keyboard but if you constantly look at the keyboard then you won't develop strong muscle memory. Now put your little fingers on the A and ; keys and start typing.",
        "text": "aaaa ;;;; aa;; ;;aa a;a; ;a;a ;a;; a;aa aaa; ;;;a",
        "category": "home-row",
        "order": 6,
        "introducedKeys": ["a", ";"],
    },
    {
        "id": "home-row-006",
        "title": "g & h keys",
        "description": "As you may have figured this out yourself, the index fingers do twice as much work as the other fingers. On the home row, the index fingers actually cover the F, G, H, and J keys. Keep you index fingers on the F and J keys and reach for the G and H keys when necessary, then return your fingers to F and J.",
        "text": "gggg hhhh gghh hhgg ghgh hghg ghgg hghh gggh hhhg",
        "category": "home-row",
        "order": 7,
        "introducedKeys": ["g", "h"],
    },
    {
        "id": "home-row-007",
        "title": "Home row mastery",
        "description": "Alright, alright, alright. Now it's time for the final test of the home row. You've learned the ten keys of the home row. It's okay if you feel like you're not fast enough yet. Keep practicing and don't give up.",
        "text": "sad lag gal lfh jfk dl; gha hhs kd; lfk dka jk; dks ajf skk ldj jfj",
        "category": "home-row",
        "order": 8,
        "introducedKeys": ["a", "s", "d", "f", "g", "h", "j", "k", "l", ";"],
    },
]